---
abstract: 'Build and use the stable 1.3.x branch of the Fast Light Toolkit'
author:
  - 'Sanko Robinson <sanko@cpan.org> - http://sankorobinson.com/'
build_requires:
  Archive::Extract: 0
  File::Copy: 0
  File::Copy::Recursive: 0
  File::ShareDir: 0
  File::Slurp: 0
  File::Spec::Functions: 0
  File::pushd: 0
  HTTP::Tiny: 0
  JSON::PP: 2
  Test::More: 0.98
configure_requires:
  Archive::Extract: 0
  CPAN::Meta: 0
  CPAN::Meta::Prereqs: 0
  Exporter: 5.57
  ExtUtils::CBuilder: 0
  ExtUtils::Config: 0.003
  ExtUtils::Helpers: 0.020
  ExtUtils::Install: 0
  ExtUtils::InstallPaths: 0.002
  ExtUtils::ParseXS: 0
  File::Basename: 0
  File::Copy: 0
  File::Copy::Recursive: 0
  File::Find: 0
  File::Path: 0
  File::ShareDir: 0
  File::Slurp: 0
  File::Spec::Functions: 0
  File::pushd: 0
  Getopt::Long: 0
  HTTP::Tiny: 0
  JSON::PP: 2
  Module::Build: 0.38
  Pod::Man: 0
  TAP::Harness: 0
dynamic_config: 0
generated_by: 'Minilla/v0.6.5, CPAN::Meta::Converter version 2.132510'
license: artistic_2
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Alien-FLTK
no_index:
  directory:
    - t
    - xt
    - inc
    - share
    - eg
    - examples
    - author
requires:
  File::ShareDir: 0
  File::Slurp: 0
  File::Spec::Functions: 0
  JSON::PP: 2
  perl: 5.008001
resources:
  bugtracker: https://github.com/sanko/alien-fltk/issues
  homepage: https://github.com/sanko/alien-fltk
  repository: git://github.com/sanko/alien-fltk.git
version: v1.3.3
